def get_study_prompts(topic: str, notes: str) -> dict:
    """Generate context-aware prompts that sync perfectly with UI sections"""
    return {
        "planning": (
            f"Create a 7-day study roadmap for: {topic}\n\n"
            f"Student materials:\n{notes[:1000]}\n\n"
            f"CRITICAL: Start your response with the EXACT header: # Study Roadmap\n\n"
            f"Requirements:\n"
            f"- Daily sessions: 60-90 minutes\n"
            f"- Prioritize high-yield exam topics first\n"
            f"- Include spaced repetition schedule\n"
            f"- Balance new content with review\n"
            f"- Flag topics needing extra focus\n"
            f"- Format as a markdown table with columns: Day | Topics | Time | Priority\n"
            f"\n"
            f"Output Format:\n"
            f"# Study Roadmap\n"
            f"\n"
            f"| Day | Topics | Time | Priority |\n"
            f"| --- | --- | --- | --- |\n"
            f"| Day 1 | ... | 60-90 min | High | \n"
        ),
        
        "summarization": (
            f"CRITICAL: Start your response with the EXACT header: # Content Analysis\n\n"
            f"Summarize these study materials about {topic} into high-yield exam content:\n\n{notes[:2000]}\n\n"
            f"Requirements:\n"
            f"- Extract key concepts, definitions, formulas\n"
            f"- Highlight exam-critical information\n"
            f"- Organize by priority: High/Medium/Low yield\n"
            f"- Keep under 600 words\n"
            f"- Use clear headings and bullet points\n"
            f"- Format as markdown\n\n"
            f"Output Format:\n"
            f"# Content Analysis\n"
            f"\n"
            f"## High-Yield Concepts\n"
            f"- [List key concepts]\n\n"
            f"## Core Definitions\n"
            f"- [List definitions]\n\n"
            f"## Critical Formulas\n"
            f"- [List formulas if applicable]"
        ),
        
        "quiz_generation": (
            f"CRITICAL: Start your response with the EXACT header: # Practice Questions\n\n"
            f"Generate 5 practice questions for {topic} based on materials:\n\n{notes[:1500]}\n\n"
            f"Requirements:\n"
            f"- Mix types: multiple choice, short answer\n"
            f"- Focus on common misconceptions\n"
            f"- Include detailed answer explanations\n"
            f"- Flag high-yield exam topics\n"
            f"- Difficulty: Medium to challenging\n\n"
            f"Output Format:\n"
            f"# Practice Questions\n"
            f"\n"
            f"**Question 1:** [Question text]\n"
            f"A) Option 1\n"
            f"B) Option 2\n"
            f"C) Option 3\n\n"
            f"**Answer:** [Correct answer with explanation]\n"
        ),
        
        "progress_tracking": (
            f"CRITICAL: Start your response with the EXACT header: # Performance Analysis\n\n"
            f"Analyze learning readiness for {topic}.\n\n"
            f"Requirements:\n"
            f"- Assign confidence scores (0-100%) to 3-5 key subtopics\n"
            f"- Identify specific knowledge gaps\n"
            f"- Recommend 2-3 targeted actions for improvement\n"
            f"- Suggest optimal next study focus\n\n"
            f"Output Format:\n"
            f"# Performance Analysis\n"
            f"\n"
            f"## Confidence Scores\n"
            f"- Topic 1: XX%\n"
            f"- Topic 2: XX%\n\n"
            f"## Knowledge Gaps\n"
            f"- [Gap 1]\n"
            f"- [Gap 2]\n\n"
            f"## Recommended Actions\n"
            f"1. [Action 1]\n"
            f"2. [Action 2]\n"
        ),
        
        "resource_finding": (
            f"CRITICAL: Start your response with the EXACT header: # Recommended Resources\n\n"
            f"Find supplementary learning resources for {topic}.\n\n"
            f"Requirements:\n"
            f"- Prioritize free, credible resources (university sites, arXiv)\n"
            f"- Include mix: video lectures, practice problems, papers\n"
            f"- Focus on resources addressing knowledge gaps\n"
            f"- Provide direct URLs and 1-sentence descriptions\n"
            f"- Limit to 3-5 highest-quality resources\n\n"
            f"Output Format:\n"
            f"# Recommended Resources\n"
            f"\n"
            f"1. **[Resource Title]**\n"
            f"   - Link: [URL]\n"
            f"   - Description: [One sentence]\n"
        )
    }
